# %CopyrightBegin%
#
# SPDX-FileCopyrightText: Copyright Ericsson AB 2023-2025. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# %CopyrightEnd%

name: Open Source Security Foundation

inputs:
    upload:
        description: 'Upload sarif results using codeql'
        default: false

runs:
    using: composite
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2
        with:
            repository: ossf/wg-best-practices-os-developers
            sparse-checkout: docs/Compiler-Hardening-Guides/compiler-options-scraper
            path: ossf
    
      - name: Setup compiler options scraper
        shell: bash -eo pipefail {0}
        run: |
          pip3 install -r ossf/docs/Compiler-Hardening-Guides/compiler-options-scraper/requirements.txt
          python3 ossf/docs/Compiler-Hardening-Guides/compiler-options-scraper/main.py
          cat compiler-options.json

      - name: Run compiler flag comparison
        shell: bash -eo pipefail {0}
        run: |
          docker run -v `pwd`/.github/scripts:/github --entrypoint "" otp \
            bash -c "/github/ossf-sarif-generator.es '$(cat compiler-options.json)'" > results.sarif

      - name: "Upload artifact"
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # ratchet:actions/upload-artifact@v4.6.1
        with:
            name: SARIF file
            path: results.sarif

      # Upload the results to GitHub's code scanning dashboard.
      - name: "Upload to code-scanning"
        if: ${{ !cancelled() && inputs.upload == 'true' }}
        uses: github/codeql-action/upload-sarif@b56ba49b26e50535fa1e7f7db0f4f7b4bf65d80d # ratchet:github/codeql-action/upload-sarif@v3.28.10
        with:
            sarif_file: results.sarif